# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build $(Build.SourcesDirectory)/time-tracker-webapi/ --configuration $(buildConfiguration)
    dotnet publish $(Build.SourcesDirectory)/time-tracker-webapi/ --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    
  displayName: 'dotnet build $(buildConfiguration)'

- task: efcore-migration-script-generator-task@0
  inputs: 
   projectpath: '$(Build.SourcesDirectory)/time-tracker-webapi/src/TimeTracker.Data/TimeTracker.Data.csproj'
   databasecontexts: 'TimeTrackerDbContext'
   startupprojectpath: '$(Build.SourcesDirectory)/time-tracker-webapi/src/TimeTracker.Api/TimeTracker.Api.csproj'
   targetfolder: '$(build.artifactstagingdirectory)/migrations'
    

- task: PublishBuildArtifacts@1
