# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  Authentication__Google__ClientId: '1234'

steps:
- script: dotnet build $(Build.SourcesDirectory)/time-tracker-webapi/ --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Npm@1
  displayName: 'npm install on package.json for frontend libs'
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)/time-tracker-webapi/src/TimeTracker.Api/'

- script: dotnet bundle $(Build.SourcesDirectory)/time-tracker-webapi/src/TimeTracker.Api/ --configuration $(buildConfiguration)
  displayName: 'bundle css and js'

- script: |
    mkdir $(Build.SourcesDirectory)/results
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  $(Build.SourcesDirectory)/time-tracker-webapi/test/TimeTracker.Api.Test/
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:MergeWtih=$(Build.SourcesDirectory)/time-tracker-webapi/test/TimeTracker.Api.Test/coverage.cobertura.xml $(Build.SourcesDirectory)/time-tracker-webapi/test/TimeTracker.Library.Test/
 #   cp $(Build.SourcesDirectory)/time-tracker-webapi/test/TimeTracker.Api.Test/coverage.cobertura.xml $(Build.SourcesDirectory)/results
 #   dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.0-rc4
 #   ./reportgenerator "-reports:$(Build.SourcesDirectory)/results/coverage.cobertura.xml" "-targetdir:results" "-reporttypes:HTMLInline;HTMLChart"
  displayName: 'Unit testing'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)/results/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/results
    codecoverageTool: cobertura

- script: dotnet publish $(Build.SourcesDirectory)/time-tracker-webapi/ --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: efcore-migration-script-generator-task@0
  inputs: 
   projectpath: '$(Build.SourcesDirectory)/time-tracker-webapi/src/TimeTracker.Data/TimeTracker.Data.csproj'
   databasecontexts: 'TimeTrackerDbContext'
   startupprojectpath: '$(Build.SourcesDirectory)/time-tracker-webapi/src/TimeTracker.Api/TimeTracker.Api.csproj'
   targetfolder: '$(build.artifactstagingdirectory)/migrations'
    

- task: PublishBuildArtifacts@1
